package com.example.laboratorinis_psk.mybatis.dao;

import com.example.laboratorinis_psk.mybatis.model.Coffeeshop;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CoffeeshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int insert(Coffeeshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    Coffeeshop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    List<Coffeeshop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int updateByPrimaryKey(Coffeeshop record);
}