package com.example.laboratorinis_psk.mybatis.dao;

import com.example.laboratorinis_psk.mybatis.model.Product;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int updateByPrimaryKey(Product record);
}