package com.example.laboratorinis_psk.mybatis.dao;

import com.example.laboratorinis_psk.mybatis.model.SupplierCoffeeshop;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SupplierCoffeeshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER_COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int insert(SupplierCoffeeshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER_COFFEESHOP
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    List<SupplierCoffeeshop> selectAll();
}