package com.example.laboratorinis_psk.mybatis.dao;

import com.example.laboratorinis_psk.mybatis.model.Supplier;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    Supplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    List<Supplier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPLIER
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    int updateByPrimaryKey(Supplier record);
}