package com.example.laboratorinis_psk.mybatis.model;

public class Coffeeshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COFFEESHOP.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COFFEESHOP.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COFFEESHOP.ID
     *
     * @return the value of PUBLIC.COFFEESHOP.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COFFEESHOP.ID
     *
     * @param id the value for PUBLIC.COFFEESHOP.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COFFEESHOP.NAME
     *
     * @return the value of PUBLIC.COFFEESHOP.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COFFEESHOP.NAME
     *
     * @param name the value for PUBLIC.COFFEESHOP.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}