package com.example.laboratorinis_psk.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @return the value of PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @param description the value for PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @return the value of PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @param price the value for PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.SHOP_ID
     *
     * @return the value of PUBLIC.PRODUCT.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.SHOP_ID
     *
     * @param shopId the value for PUBLIC.PRODUCT.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}