package com.example.laboratorinis_psk.mybatis.model;

public class SupplierCoffeeshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUPPLIER_COFFEESHOP.SUPPLIERS_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Integer suppliersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUPPLIER_COFFEESHOP.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUPPLIER_COFFEESHOP.SUPPLIERS_ID
     *
     * @return the value of PUBLIC.SUPPLIER_COFFEESHOP.SUPPLIERS_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Integer getSuppliersId() {
        return suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUPPLIER_COFFEESHOP.SUPPLIERS_ID
     *
     * @param suppliersId the value for PUBLIC.SUPPLIER_COFFEESHOP.SUPPLIERS_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setSuppliersId(Integer suppliersId) {
        this.suppliersId = suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUPPLIER_COFFEESHOP.SHOP_ID
     *
     * @return the value of PUBLIC.SUPPLIER_COFFEESHOP.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUPPLIER_COFFEESHOP.SHOP_ID
     *
     * @param shopId the value for PUBLIC.SUPPLIER_COFFEESHOP.SHOP_ID
     *
     * @mbg.generated Mon May 08 22:09:52 EEST 2023
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}